languageCode = "de-de"
DefaultContentLanguage = "de-de"
title = "safeMarket"
themesDir = "themes"
theme = "hugo-hero-theme"
baseUrl = "/"

[languages]
  [languages.de-de]
    languageName = "DE"
    title = "SafeMarket"
    weight = 1
  [languages.en]
    languageName = "EN"
    title = "SafeMarket"
    weight = 0

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "SafeMarket - Zuhause Schlange stehen"
    meta_og_title = "SafeMarket"
    meta_og_type = "website"
    meta_og_url = "https://safemarket.onrender.com"
    meta_og_image = "https://safemarket.onrender.com/images/logo.svg"
    meta_og_description = "SafeMarket - Zuhause Schlange stehen"

[permalinks]
  post = ":year/:month/:day/:slug/"
  pages = "/:filename/"